/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven("https://maven.aliyun.com/repository/public")
    maven("https://repo.maven.apache.org/maven2/")
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:2.6.7")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.6.7")
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
description = "java-docs-spring-hello-world"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
