/*
 * This file was generated by the Gradle 'init' task.
 * This project uses @Incubating APIs which are subject to change.
 */
pluginManagement {
    repositories {
        maven("https://maven.aliyun.com/repository/public")
        maven("https://maven.aliyun.com/repository/gradle-plugin")
        gradlePluginPortal()
    }
}

rootProject.name = "java-docs-spring-hello-world"
